-- Backing migration for the dark-launched AI Website lead-capture feature.
--
-- The AiWebsiteLead / AiWebsiteEvent models (schema.prisma) and their consumers
-- (app/api/ai-website/lead/route.ts, src/lib/ai-website/notifier.ts) shipped
-- WITHOUT this migration, so the tables never existed in prod. The feature is
-- dark-by-default (404 until AI_WEBSITE_ENABLED=true, see src/lib/ai-website/
-- flags.ts) — but the moment the flag is switched on, prisma.aiWebsiteLead.create()
-- would throw P2021 (relation does not exist). This migration makes the feature
-- actually work when enabled and resolves the schema drift the CI gate now catches.
--
-- Purely additive (two new tables + their indexes + one FK); no existing table is
-- touched, so it cannot abort the deploy. SQL generated by Prisma migrate diff
-- (canonical form → future migrate diff sees zero drift).
-- Rollback: DROP TABLE "ai_website_events"; DROP TABLE "ai_website_leads";

-- CreateTable
CREATE TABLE "ai_website_leads" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "role" TEXT,
    "source" TEXT NOT NULL DEFAULT 'ai-website',
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL DEFAULT 'new',
    "advisor_pathway" TEXT,
    "meta" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_website_leads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_website_events" (
    "id" UUID NOT NULL,
    "lead_id" UUID NOT NULL,
    "kind" TEXT NOT NULL,
    "channel" TEXT,
    "detail" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_website_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ai_website_leads_email_idx" ON "ai_website_leads"("email");

-- CreateIndex
CREATE INDEX "ai_website_leads_status_created_at_idx" ON "ai_website_leads"("status", "created_at");

-- CreateIndex
CREATE INDEX "ai_website_events_lead_id_created_at_idx" ON "ai_website_events"("lead_id", "created_at");

-- AddForeignKey
ALTER TABLE "ai_website_events" ADD CONSTRAINT "ai_website_events_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "ai_website_leads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
