import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlertTriangle,
  Baby,
  Briefcase,
  Building,
  Building2,
  FileCheck,
  GraduationCap,
  HardHat,
  Heart,
  Home,
  Hotel,
  Layers,
  Pickaxe,
  Shield,
  Sparkles,
  Stethoscope,
  Store,
  Tent,
  Wrench,
} from 'lucide-react';

/** Course-area chips on the industries hub — never IICRC designation acronyms. */
export type IndustryHubCard = {
  slug: string;
  label: string;
  description: string;
  Icon: LucideIcon;
  color: string;
  areas: readonly string[];
};

export const industryHubCards: IndustryHubCard[] = [
  {
    slug: 'healthcare',
    label: 'Healthcare',
    description: 'Hospitals, clinics, medical facilities',
    Icon: Stethoscope,
    color: '#009688',
    areas: ['Mould', 'Water damage', 'Indoor air quality'],
  },
  {
    slug: 'aged-care',
    label: 'Aged Care',
    description: 'Residential aged care facilities',
    Icon: Shield,
    color: '#27ae60',
    areas: ['Mould', 'Carpet hygiene', 'PPE'],
  },
  {
    slug: 'hospitality',
    label: 'Hotels & Resorts',
    description: 'Hotels, resorts, casinos, cruise ships',
    Icon: Hotel,
    color: '#8e44ad',
    areas: ['Water damage', 'Odour control', 'Structural drying'],
  },
  {
    slug: 'facility-management',
    label: 'Facility management',
    description: 'Contract managers and the crews on their sites',
    Icon: Briefcase,
    color: '#0f5fa8',
    areas: ['Team records', 'CEC tracking', 'Site evidence'],
  },
  {
    slug: 'government-defence',
    label: 'Government & Defence',
    description: 'Councils, state agencies, defence',
    Icon: Building2,
    color: '#2196f3',
    areas: ['Mould', 'Water damage', 'Fire and smoke'],
  },
  {
    slug: 'commercial-cleaning',
    label: 'Commercial Cleaning',
    description: 'Cleaning contractors, facility services',
    Icon: Sparkles,
    color: '#2490ed',
    areas: ['Carpet care', 'Water damage', 'Mould'],
  },
  {
    slug: 'education',
    label: 'Education',
    description: 'Schools, universities',
    Icon: GraduationCap,
    color: '#3498db',
    areas: ['Mould', 'Water damage', 'Carpet care'],
  },
  {
    slug: 'insurance',
    label: 'Insurance',
    description: 'Loss adjusters, claims assessors',
    Icon: FileCheck,
    color: '#16a085',
    areas: ['Water damage', 'Fire and smoke', 'Structural drying'],
  },
  {
    slug: 'strata',
    label: 'Strata & Body Corporate',
    description: 'Building managers, body corporate',
    Icon: Layers,
    color: '#9b59b6',
    areas: ['Water damage', 'Carpet care', 'Mould'],
  },
  {
    slug: 'mining',
    label: 'Mining & Resources',
    description: 'Mine camps, remote facilities',
    Icon: Pickaxe,
    color: '#ed9d24',
    areas: ['Water damage', 'Structural drying', 'Mould'],
  },
  {
    slug: 'retail',
    label: 'Retail & Shopping Centres',
    description: 'Shopping centres, major landlords',
    Icon: Store,
    color: '#e74c3c',
    areas: ['Water damage', 'Odour control', 'Fire and smoke'],
  },
  {
    slug: 'childcare',
    label: 'Childcare',
    description: 'Early childhood centres',
    Icon: Baby,
    color: '#e91e63',
    areas: ['Carpet care', 'Mould'],
  },
  {
    slug: 'construction',
    label: 'Construction',
    description: 'Builders, construction sites',
    Icon: HardHat,
    color: '#ff9800',
    areas: ['Water damage', 'Structural drying'],
  },
  {
    slug: 'property-management',
    label: 'Property Management',
    description: 'Property managers, real estate',
    Icon: Building,
    color: '#673ab7',
    areas: ['Water damage', 'Carpet care', 'Structural drying'],
  },
  {
    slug: 'plumbing-trades',
    label: 'Plumbing & Trades',
    description: 'Plumbers, trade contractors',
    Icon: Wrench,
    color: '#0097a7',
    areas: ['Water damage', 'Structural drying', 'Mould'],
  },
  {
    slug: 'ndis-disability',
    label: 'NDIS & Disability Services',
    description: 'SIL, SDA, disability providers',
    Icon: Heart,
    color: '#5c6bc0',
    areas: ['Mould', 'Water damage', 'Carpet care'],
  },
  {
    slug: 'gyms-fitness',
    label: 'Gyms & Fitness Centres',
    description: 'Gyms, pools, fitness facilities',
    Icon: Activity,
    color: '#43a047',
    areas: ['Mould', 'Odour control', 'Carpet care'],
  },
  {
    slug: 'real-estate',
    label: 'Real Estate & Property Sales',
    description: 'Real estate agents, conveyancers',
    Icon: Home,
    color: '#ff7043',
    areas: ['Water damage', 'Structural drying', 'Mould'],
  },
  {
    slug: 'emergency-management',
    label: 'Emergency Management & SES',
    description: 'SES, councils, emergency teams',
    Icon: AlertTriangle,
    color: '#ef5350',
    areas: ['Water damage', 'Fire and smoke', 'Structural drying'],
  },
  {
    slug: 'caravan-parks',
    label: 'Caravan Parks & Holiday Stays',
    description: 'Caravan parks, holiday accommodation',
    Icon: Tent,
    color: '#26a69a',
    areas: ['Mould', 'Carpet care', 'Water damage'],
  },
];
