/**
 * Remove AI vendor documentation citations and similar attribution from
 * learner-facing course and lesson text (references, footers, overview copy).
 */

const VENDOR_DOC_REF_PARTS = [
  /\s*\|\s*Anthropic Claude documentation/gi,
  /\s*\|\s*OpenAI ChatGPT documentation/gi,
  /Anthropic Claude documentation\s*\|\s*/gi,
  /OpenAI ChatGPT documentation\s*\|\s*/gi,
  /^Reference:\s*Anthropic Claude documentation\s*\|\s*OpenAI ChatGPT documentation\s*\|\s*/im,
  /^Reference:\s*OpenAI ChatGPT documentation\s*\|\s*Anthropic Claude documentation\s*\|\s*/im,
];

const PROSE_REPLACEMENTS: Array<[RegExp, string]> = [
  [
    /conversational AI assistants such as Claude \(Anthropic\) and ChatGPT \(OpenAI\)/gi,
    'conversational AI assistants',
  ],
  [
    /specifically conversational AI assistants such as Claude \(Anthropic\) and ChatGPT \(OpenAI\)/gi,
    'conversational AI assistants',
  ],
  [
    /AI language tools — specifically ChatGPT and Claude —/gi,
    'AI language tools — specifically conversational AI assistants —',
  ],
  [
    /AI language tools — ChatGPT, Claude, Gemini —/gi,
    'AI language tools — leading conversational AI assistants —',
  ],
  [
    /for interacting with ChatGPT \(and other AI language model tools\)/gi,
    'for interacting with conversational AI language model tools',
  ],
  [
    /written with (?:Anthropic )?Claude|generated by (?:Anthropic )?Claude|content (?:was )?written with Anthropic/gi,
    'developed by CARSI',
  ],
];

const VENDOR_REF_PART =
  /^(?:anthropic claude documentation|openai chatgpt documentation)$/i;

function tidyReferenceLine(text: string): string {
  let out = text;
  for (const re of VENDOR_DOC_REF_PARTS) {
    out = out.replace(re, (match) => (match.trimStart().startsWith('Reference:') ? 'Reference: ' : ' | '));
  }

  out = out
    .split('\n')
    .map((line) => {
      if (!/^Reference:/i.test(line)) return line;
      const parts = line
        .replace(/^Reference:\s*/i, '')
        .split('|')
        .map((p) => p.trim())
        .filter((p) => p && !VENDOR_REF_PART.test(p));
      return parts.length > 0 ? `Reference: ${parts.join(' | ')}` : line;
    })
    .join('\n');

  return out;
}

/** Sanitize plain-text lesson or course body before seeding or display. */
export function sanitizeLearnerContent(text: string | null | undefined): string | null {
  if (!text?.trim()) return text ?? null;

  let out = text;
  for (const [re, replacement] of PROSE_REPLACEMENTS) {
    out = out.replace(re, replacement);
  }
  out = tidyReferenceLine(out);

  return out.trim() || null;
}
