apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carsi-ingress
  namespace: carsi-production
  labels:
    app.kubernetes.io/part-of: carsi-lms
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - carsi.com.au
        - api.carsi.com.au
      secretName: carsi-tls
  rules:
    - host: carsi.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carsi-web
                port:
                  number: 3000
    - host: api.carsi.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carsi-backend
                port:
                  number: 8000
