apiVersion: v1
kind: Service
metadata:
  name: carsi-web
  namespace: carsi-production
  labels:
    app: carsi-web
    app.kubernetes.io/part-of: carsi-lms
spec:
  type: ClusterIP
  selector:
    app: carsi-web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: carsi-backend
  namespace: carsi-production
  labels:
    app: carsi-backend
    app.kubernetes.io/part-of: carsi-lms
spec:
  type: ClusterIP
  selector:
    app: carsi-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: carsi-postgres
  namespace: carsi-production
  labels:
    app: carsi-postgres
    app.kubernetes.io/part-of: carsi-lms
spec:
  type: ClusterIP
  selector:
    app: carsi-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: carsi-redis
  namespace: carsi-production
  labels:
    app: carsi-redis
    app.kubernetes.io/part-of: carsi-lms
spec:
  type: ClusterIP
  selector:
    app: carsi-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
