/**
 * Remove AI vendor documentation citations from learner-facing LMS text in PostgreSQL.
 *
 *   npx tsx scripts/strip-ai-vendor-references-from-lms.ts
 *   npx tsx scripts/strip-ai-vendor-references-from-lms.ts --dry-run
 */
import 'dotenv/config';

import { prisma } from '@/lib/prisma';
import { sanitizeLearnerContent } from '@/lib/seed/sanitize-learner-content';

async function main() {
  const dryRun = process.argv.includes('--dry-run');

  if (!process.env.DATABASE_URL?.trim()) {
    console.error('DATABASE_URL is required.');
    process.exit(1);
  }

  let lessonUpdates = 0;
  let courseUpdates = 0;

  const lessons = await prisma.lmsLesson.findMany({
    where: { contentBody: { not: null } },
    select: { id: true, title: true, contentBody: true },
  });

  const needsSanitize = (text: string) =>
    /anthropic|openai chatgpt documentation|claude documentation|written with anthropic|generated by anthropic|content written with|^Reference:\s*\|/im.test(
      text
    );

  for (const lesson of lessons) {
    const body = lesson.contentBody;
    if (!body || !needsSanitize(body)) continue;

    const cleaned = sanitizeLearnerContent(body);
    if (!cleaned || cleaned === body) continue;

    lessonUpdates += 1;
    console.log(`Lesson: ${lesson.title}`);
    if (!dryRun) {
      await prisma.lmsLesson.update({
        where: { id: lesson.id },
        data: { contentBody: cleaned },
      });
    }
  }

  const courses = await prisma.lmsCourse.findMany({
    select: {
      id: true,
      slug: true,
      title: true,
      description: true,
      shortDescription: true,
    },
  });

  for (const course of courses) {
    const fields: { description?: string | null; shortDescription?: string | null } = {};
    let changed = false;

    for (const key of ['description', 'shortDescription'] as const) {
      const raw = course[key];
      if (!raw || !needsSanitize(raw)) continue;
      const cleaned = sanitizeLearnerContent(raw);
      if (cleaned && cleaned !== raw) {
        fields[key] = cleaned;
        changed = true;
      }
    }

    if (!changed) continue;
    courseUpdates += 1;
    console.log(`Course: ${course.slug}`);
    if (!dryRun) {
      await prisma.lmsCourse.update({ where: { id: course.id }, data: fields });
    }
  }

  console.log(
    dryRun
      ? `Dry run — would update ${lessonUpdates} lesson(s), ${courseUpdates} course(s).`
      : `Updated ${lessonUpdates} lesson(s), ${courseUpdates} course(s).`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
