/**
 * Model Currency Check
 * Compares configured AI models against approved defaults.
 * Generates reports/model-currency-report.md.
 *
 * Run via: pnpm ai:models:check
 * @see memory.md > Visual Excellence and Model Currency Protocol
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { APPROVED_MODELS, isModelCurrent, type ModelStatus } from '../model-registry/index';

interface ConfiguredModel {
  taskType: string;
  modelId: string;
  source: string; // where this config was found
}

interface ModelAuditResult {
  configured: ConfiguredModel;
  approvedDefault: string;
  status: ModelStatus;
  action: string;
}

const PROJECT_ROOT = join(__dirname, '../../..');

/**
 * Read configured models from .env files.
 */
function readConfiguredModels(): ConfiguredModel[] {
  const models: ConfiguredModel[] = [];

  // Read backend .env.local
  const backendEnv = join(PROJECT_ROOT, 'apps/backend/.env.local');
  if (existsSync(backendEnv)) {
    const content = readFileSync(backendEnv, 'utf-8');
    const lines = content.split('\n');

    for (const line of lines) {
      const [key, value] = line.split('=').map((s) => s.trim());
      if (!key || !value) continue;

      if (key === 'OLLAMA_MODEL') {
        models.push({ taskType: 'local-inference', modelId: value, source: 'backend/.env.local' });
      }
      if (key === 'AI_PROVIDER') {
        // Record provider selection
        models.push({
          taskType: 'provider-selection',
          modelId: value,
          source: 'backend/.env.local',
        });
      }
    }
  }

  return models;
}

/**
 * Audit a configured model against approved defaults.
 */
function auditModel(configured: ConfiguredModel): ModelAuditResult {
  const approved = APPROVED_MODELS.find((m) => m.taskTypes.includes(configured.taskType as never));

  const status = isModelCurrent(configured.modelId);

  return {
    configured,
    approvedDefault: approved?.id ?? 'No approved default for this task type',
    status,
    action:
      status === 'current'
        ? 'None required'
        : status === 'deprecated'
          ? `URGENT: Replace with ${approved?.id ?? 'approved alternative'}`
          : status === 'review-needed'
            ? 'Review model against current approved defaults'
            : 'Model not in registry — verify manually',
  };
}

/**
 * Generate the model currency report.
 */
function generateReport(results: ModelAuditResult[]): string {
  const now = new Date();
  const dateStr = `${now.getDate().toString().padStart(2, '0')}/${(now.getMonth() + 1).toString().padStart(2, '0')}/${now.getFullYear()} ${now.toTimeString().slice(0, 5)} AEST`;

  const total = results.length;
  const current = results.filter((r) => r.status === 'current').length;
  const reviewNeeded = results.filter((r) => r.status === 'review-needed').length;
  const deprecated = results.filter((r) => r.status === 'deprecated').length;
  const unknown = results.filter((r) => r.status === 'unknown').length;

  const rows = results
    .map((r) => {
      const icon =
        r.status === 'current'
          ? '✅'
          : r.status === 'deprecated'
            ? '🔴'
            : r.status === 'review-needed'
              ? '⚠️'
              : '❓';
      return `| ${r.configured.taskType} | ${r.configured.modelId} | ${r.approvedDefault} | ${icon} ${r.status} |`;
    })
    .join('\n');

  const actions = results
    .filter((r) => r.status !== 'current')
    .map((r, i) => `${i + 1}. [${r.status.toUpperCase()}] ${r.configured.modelId}: ${r.action}`)
    .join('\n');

  const nextReview = new Date(now);
  nextReview.setDate(nextReview.getDate() + 30);
  const nextReviewStr = `${nextReview.getDate().toString().padStart(2, '0')}/${(nextReview.getMonth() + 1).toString().padStart(2, '0')}/${nextReview.getFullYear()}`;

  return `# Model Currency Report

Generated: ${dateStr}

## Summary

- Configured models: ${total}
- Current: ${current} ✅
- Review needed: ${reviewNeeded} ⚠️
- Deprecated: ${deprecated} 🔴
- Unknown: ${unknown} ❓

## Model Audit

| Task Type | Configured Model | Approved Default | Status |
|---|---|---|---|
${rows}

## Required Actions

${actions.length > 0 ? actions : 'No actions required — all models current.'}

## Approved Model Registry

${APPROVED_MODELS.map((m) => `- **${m.id}** (${m.provider}): ${m.notes ?? ''}`).join('\n')}

## Next Review

Recommended: ${nextReviewStr}

*Generated by \`pnpm ai:models:check\` — see \`src/ai/version-checks/check-model-currency.ts\`*
`;
}

/**
 * Main entry point.
 */
function main(): void {
  console.log('🔍 Running model currency check...\n');

  const configured = readConfiguredModels();

  if (configured.length === 0) {
    console.log('⚠️  No configured models found. Check .env.local files.\n');
  }

  const results = configured.map(auditModel);

  // Ensure reports directory exists
  const reportsDir = join(PROJECT_ROOT, 'reports');
  if (!existsSync(reportsDir)) {
    mkdirSync(reportsDir, { recursive: true });
  }

  const reportPath = join(reportsDir, 'model-currency-report.md');
  const report = generateReport(results);
  writeFileSync(reportPath, report, 'utf-8');

  console.log('📊 Model Currency Report\n');
  console.log(report);
  console.log(`\n✅ Report saved to: reports/model-currency-report.md`);

  // Exit with error if any deprecated models
  const hasDeprecated = results.some((r) => r.status === 'deprecated');
  if (hasDeprecated) {
    console.error('\n🔴 DEPRECATED MODELS FOUND — review required before AI tasks');
    process.exit(1);
  }
}

main();
